<?php
// ACF Options

if (function_exists('acf_add_options_page')) {


	acf_add_options_page(array(
		'page_title' 	=> 'Site Settings',
		'menu_title'	=> 'Site Settings',
		'menu_slug' 	=> 'site-settings',
		'capability'	=> 'edit_posts',
		'redirect'		=> false
	));
}

// Point ACF to the theme's acf-json folder for both load and save
add_filter('acf/settings/save_json', function () {
	return get_stylesheet_directory() . '/acf-json';
});

add_filter('acf/settings/load_json', function ($paths) {
	$paths[] = get_stylesheet_directory() . '/acf-json';
	return $paths;
});

// the ACF fields

if (function_exists('acf_add_local_field_group')):

	acf_add_local_field_group(array(
		'key' => 'group_562fb3f3bc547',
		'title' => 'Code snippets: Body',
		'fields' => array(
			array(
				'key' => 'field_562fb3f3bfa7f',
				'label' => 'Code Snippets',
				'name' => 'code_snippets__body',
				'type' => 'repeater',
				'instructions' => 'Add code that belongs before the closing &lt;body&gt; tag',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => '+ Add Snippet',
				'sub_fields' => array(
					array(
						'key' => 'field_562fb3f3c14f9',
						'label' => 'Code',
						'name' => 'code',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
				'collapsed' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-body-tag',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_562f9de4e4fbb',
		'title' => 'Code snippets: Head',
		'fields' => array(
			array(
				'key' => 'field_562f9deba8199',
				'label' => 'Code Snippets',
				'name' => 'code_snippets__head',
				'type' => 'repeater',
				'instructions' => 'Add code that belongs inside &lt;head&gt; tags',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => '+ Add Snippet',
				'sub_fields' => array(
					array(
						'key' => 'field_562f9df9a819a',
						'label' => 'Code',
						'name' => 'code',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
				'collapsed' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-head-tag',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5a57b204b40b9',
		'title' => 'Code snippets: After head',
		'fields' => array(
			array(
				'key' => 'field_5a57b204b9ca0',
				'label' => 'Code Snippets',
				'name' => 'code_snippets__head_after',
				'type' => 'repeater',
				'instructions' => 'Add code that belongs immediately after the &lt;/head&gt; tag',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => '+ Add Snippet',
				'sub_fields' => array(
					array(
						'key' => 'field_5a57b204bcd22',
						'label' => 'Code',
						'name' => 'code',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-head-tag',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	// ── Page Settings ───────────────────────────────────────────────────
	acf_add_local_field_group(array(
		'key'    => 'group_page_settings',
		'title'  => 'Page Settings',
		'fields' => array(
			array(
				'key'               => 'field_page_banner_sub_title',
				'label'             => 'Banner Sub Title',
				'name'              => 'banner_sub_title',
				'type'              => 'text',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '70', 'class' => '', 'id' => ''),
				'default_value'     => '',
				'placeholder'       => '',
			),
			array(
				'key'           => 'field_page_banner_image',
				'label'         => 'Image',
				'name'          => 'image',
				'type'          => 'image',
				'required'      => 0,
				'conditional_logic' => 0,
				'wrapper'       => array('width' => '30', 'class' => '', 'id' => ''),
				'return_format' => 'array',
				'preview_size'  => 'thumbnail',
				'library'       => 'all',
				'min_width'     => '',
				'min_height'    => '',
				'min_size'      => '',
				'max_width'     => '',
				'max_height'    => '',
				'max_size'      => '',
				'mime_types'    => 'jpg, jpeg, png, svg, webp',
			),
			array(
				'key'               => 'field_page_banner_title',
				'label'             => 'Banner Title',
				'name'              => 'banner_title',
				'type'              => 'text',
				'required'          => 0,
				'conditional_logic' => 0,
				'default_value'     => '',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_page_description',
				'label'             => 'Description',
				'name'              => 'description',
				'type'              => 'textarea',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '60', 'class' => '', 'id' => ''),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 4,
				'new_lines'         => 'wpautop',
			),
			array(
				'key'               => 'field_page_banner_cta',
				'label'             => 'Banner CTA',
				'name'              => 'banner_cta',
				'type'              => 'repeater',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '40', 'class' => '', 'id' => ''),
				'min'               => 0,
				'max'               => 0,
				'layout'            => 'row',
				'button_label'      => '+ Add Link',
				'sub_fields'        => array(
					array(
						'key'               => 'field_page_banner_cta_link',
						'label'             => 'Link',
						'name'              => 'link',
						'type'              => 'link',
						'required'          => 0,
						'conditional_logic' => 0,
						'return_format'     => 'array',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'active'                => 1,
	));

	// ── Site Settings ───────────────────────────────────────────────────
	acf_add_local_field_group(array(
		'key'    => 'group_site_settings',
		'title'  => 'Site Settings',
		'fields' => array(
			array(
				'key'               => 'field_site_tab_header',
				'label'             => 'Header',
				'name'              => '',
				'type'              => 'tab',
				'required'          => 0,
				'conditional_logic' => 0,
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'           => 'field_site_logo',
				'label'         => 'Logo',
				'name'          => 'site_logo',
				'type'          => 'image',
				'required'      => 0,
				'conditional_logic' => 0,
				'wrapper'       => array('width' => '30', 'class' => '', 'id' => ''),
				'return_format' => 'array',
				'preview_size'  => 'thumbnail',
				'library'       => 'all',
				'min_width'     => '',
				'min_height'    => '',
				'min_size'      => '',
				'max_width'     => '',
				'max_height'    => '',
				'max_size'      => '',
				'mime_types'    => 'jpg, jpeg, png, svg, webp',
			),
			array(
				'key'               => 'field_site_donate_link',
				'label'             => 'Donate Link',
				'name'              => 'donate_link',
				'type'              => 'link',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '70', 'class' => '', 'id' => ''),
				'return_format'     => 'array',
			),
			array(
				'key'               => 'field_site_cta_links',
				'label'             => 'CTA Links',
				'name'              => 'cta_links',
				'type'              => 'repeater',
				'required'          => 0,
				'conditional_logic' => 0,
				'min'               => 0,
				'max'               => 0,
				'layout'            => 'row',
				'button_label'      => '+ Add Link',
				'sub_fields'        => array(
					array(
						'key'           => 'field_site_cta_link',
						'label'         => 'Link',
						'name'          => 'link',
						'type'          => 'link',
						'required'      => 0,
						'conditional_logic' => 0,
						'return_format' => 'array',
					),
				),
			),
			array(
				'key'               => 'field_site_tab_footer',
				'label'             => 'Footer',
				'name'              => '',
				'type'              => 'tab',
				'required'          => 0,
				'conditional_logic' => 0,
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_site_footer_textarea',
				'label'             => 'Footer Content',
				'name'              => 'footer_content',
				'type'              => 'textarea',
				'required'          => 0,
				'conditional_logic' => 0,
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 4,
				'new_lines'         => 'wpautop',
			),
			array(
				'key'               => 'field_site_instagram_url',
				'label'             => 'Instagram URL',
				'name'              => 'instagram_url',
				'type'              => 'url',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '33', 'class' => '', 'id' => ''),
				'default_value'     => '',
				'placeholder'       => 'https://instagram.com/',
			),
			array(
				'key'               => 'field_site_twitter_url',
				'label'             => 'Twitter URL',
				'name'              => 'twitter_url',
				'type'              => 'url',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '33', 'class' => '', 'id' => ''),
				'default_value'     => '',
				'placeholder'       => 'https://twitter.com/',
			),
			array(
				'key'               => 'field_site_facebook_url',
				'label'             => 'Facebook URL',
				'name'              => 'facebook_url',
				'type'              => 'url',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '33', 'class' => '', 'id' => ''),
				'default_value'     => '',
				'placeholder'       => 'https://facebook.com/',
			),
			array(
				'key'               => 'field_site_tab_footer_banner',
				'label'             => 'Footer Banner',
				'name'              => '',
				'type'              => 'tab',
				'required'          => 0,
				'conditional_logic' => 0,
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_site_footer_banner_title',
				'label'             => 'Banner Title',
				'name'              => 'footer_banner_title',
				'type'              => 'text',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '70', 'class' => '', 'id' => ''),
				'default_value'     => '',
				'placeholder'       => '',
			),
			array(
				'key'           => 'field_site_footer_banner_image',
				'label'         => 'Image',
				'name'          => 'footer_banner_image',
				'type'          => 'image',
				'required'      => 0,
				'conditional_logic' => 0,
				'wrapper'       => array('width' => '30', 'class' => '', 'id' => ''),
				'return_format' => 'array',
				'preview_size'  => 'thumbnail',
				'library'       => 'all',
				'min_width'     => '',
				'min_height'    => 	'',
				'min_size'      => '',
				'max_width'     => 	'',
				'max_height'    => 	'',
				'max_size'      => '',
				'mime_types'    => 'jpg, jpeg, png, svg, webp',
			),
			array(
				'key'               => 'field_site_footer_banner_description',
				'label'             => 'Banner Description',
				'name'              => 'footer_banner_description',
				'type'              => 'textarea',
				'required'          => 0,
				'conditional_logic' => 0,
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 4,
				'new_lines'         => 'wpautop',
			),
			array(
				'key'               => 'field_site_footer_banner_app_store',
				'label'             => 'App Store',
				'name'              => 'app_store',
				'type'              => 'url',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '50', 'class' => '', 'id' => ''),
				'default_value'     => '',
				'placeholder'       => 'https://',
			),
			array(
				'key'               => 'field_site_footer_banner_play_store',
				'label'             => 'Play Store',
				'name'              => 'play_store',
				'type'              => 'url',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '50', 'class' => '', 'id' => ''),
				'default_value'     => '',
				'placeholder'       => 'https://',
			),
		),
		'location' => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'site-settings',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'active'                => 1,
	));

	// ── Featured Books Block ─────────────────────────────────────────────
	acf_add_local_field_group(array(
		'key'      => 'group_featured_books_block',
		'title'    => 'Featured Books Block',
		'fields'   => array(
			array(
				'key'           => 'field_fbb_source',
				'label'         => 'Books Source',
				'name'          => 'book_source',
				'type'          => 'radio',
				'required'      => 0,
				'conditional_logic' => 0,
				'choices'       => array(
					'automatic' => 'Automatic',
					'manual'    => 'Manual',
				),
				'default_value' => 'automatic',
				'return_format' => 'value',
				'allow_null'    => 0,
				'layout'        => 'horizontal',
			),
			array(
				'key'               => 'field_fbb_auto_message',
				'label'             => '',
				'name'              => 'auto_message',
				'type'              => 'message',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_fbb_source',
							'operator' => '==',
							'value'    => 'automatic',
						),
					),
				),
				'message'    => 'Automatic display books',
				'new_lines'  => 'wpautop',
				'esc_html'   => 0,
			),
			array(
				'key'               => 'field_fbb_manual_books',
				'label'             => 'Select Books',
				'name'              => 'manual_books',
				'type'              => 'relationship',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_fbb_source',
							'operator' => '==',
							'value'    => 'manual',
						),
					),
				),
				'post_type'     => array('post'),
				'filters'       => array('search'),
				'return_format' => 'object',
				'elements'      => array('featured_image'),
			),
		),
		'location' => array(
			array(
				array(
					'param'    => 'block',
					'operator' => '==',
					'value'    => 'acf/featured-books-block',
				),
			),
		),
		'menu_order'          => 0,
		'position'            => 'normal',
		'style'               => 'default',
		'label_placement'     => 'top',
		'instruction_placement' => 'label',
		'active'              => 1,
	));

	// ── Categories Books Block ───────────────────────────────────────────
	acf_add_local_field_group(array(
		'key'    => 'group_categories_books_block',
		'title'  => 'Categories Books Block',
		'fields' => array(
			array(
				'key'               => 'field_cbb_block_title',
				'label'             => 'Block Title',
				'name'              => 'block_title',
				'type'              => 'text',
				'required'          => 0,
				'conditional_logic' => 0,
				'default_value'     => '',
				'placeholder'       => 'e.g. Browse by Category',
			),
			array(
				'key'               => 'field_cbb_show_slider',
				'label'             => 'Show CTA',
				'name'              => 'show_slider',
				'type'              => 'checkbox',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '33', 'class' => '', 'id' => ''),
				'choices'           => array('yes' => 'Show CTA'),
				'default_value'     => array(),
				'return_format'     => 'value',
				'layout'            => 'vertical',
				'toggle'            => 0,
			),
			array(
				'key'               => 'field_cbb_background',
				'label'             => 'Select Background',
				'name'              => 'background',
				'type'              => 'button_group',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '33', 'class' => '', 'id' => ''),
				'choices'           => array(
					'white'      => 'White',
					'light_gray' => 'Light Gray',
				),
				'default_value' => 'white',
				'return_format' => 'value',
				'layout'        => 'horizontal',
			),
			array(
				'key'               => 'field_cbb_source',
				'label'             => 'Books Source',
				'name'              => 'book_source',
				'type'              => 'radio',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array('width' => '33', 'class' => '', 'id' => ''),
				'choices'           => array(
					'manual'        => 'Manual',
					'from_category' => 'From Category',
				),
				'default_value' => 'manual',
				'return_format' => 'value',
				'allow_null'    => 0,
				'layout'        => 'horizontal',
			),
			array(
				'key'               => 'field_cbb_manual_books',
				'label'             => 'Select Books',
				'name'              => 'manual_books',
				'type'              => 'relationship',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_cbb_source',
							'operator' => '==',
							'value'    => 'manual',
						),
					),
				),
				'post_type'     => array('post'),
				'filters'       => array('search'),
				'return_format' => 'object',
				'elements'      => array('featured_image'),
			),
			array(
				'key'               => 'field_cbb_categories',
				'label'             => 'Select Categories',
				'name'              => 'book_categories',
				'type'              => 'taxonomy',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_cbb_source',
							'operator' => '==',
							'value'    => 'from_category',
						),
					),
				),
				'taxonomy'      => 'category',
				'add_term'      => 0,
				'save_terms'    => 0,
				'load_terms'    => 0,
				'return_format' => 'id',
				'field_type'    => 'checkbox',
				'allow_null'    => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param'    => 'block',
					'operator' => '==',
					'value'    => 'acf/categories-books-block',
				),
			),
		),
		'menu_order'          => 0,
		'position'            => 'normal',
		'style'               => 'default',
		'label_placement'     => 'top',
		'instruction_placement' => 'label',
		'active'              => 1,
	));

endif;
